import Head from 'next/head'
import { useRouter } from 'next/router';
import { useState } from 'react';
import { useQuestions } from '../context/useQuestions';

export default function Home() {
  const [question, setQuestion] = useState<string>('1');
  const { push } = useRouter();
  const { fetchQuestions, questions } = useQuestions();

  const onSubmit = (e): void => {
    e.preventDefault();
    fetchQuestions(question)
    push('/start')
  }

  return (
    <div>
      <Head>
        <title>waProjet</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <form onSubmit={onSubmit}>
        <label>
          How many questions?
          <input
            type="number"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
          />
        </label>
        <button type="submit">submit</button>
      </form>
    </div>
  )
}
